"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class to_piemos(object):
    __slots__ = ["auton", "enabled"]

    def __init__(self):
        self.auton = False
        self.enabled = False

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(to_piemos._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.auton, self.enabled))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != to_piemos._get_packed_fingerprint():
            raise ValueError("Decode error")
        return to_piemos._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = to_piemos()
        self.auton, self.enabled = struct.unpack(">bb", buf.read(2))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if to_piemos in parents: return 0
        tmphash = (0xeb14b16a5128fb9c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if to_piemos._packed_fingerprint is None:
            to_piemos._packed_fingerprint = struct.pack(">Q", to_piemos._get_hash_recursive([]))
        return to_piemos._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

